flatschedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('schedule/', include("schedule.urls")),
    path('admin/', admin.site.urls),
]

schedule/urls.py
from django.urls import path

from . import views

app_name = "schedule"
urlpatterns = [
    path('', views.index, name="index"),
    path("<int:room_id>/done", views.done, name="done"),
    path("<int:room_id>/rotate", views.rotate, name="rotate"),
    path("<int:c_id>/hold", views.hold, name="hold"),
    path("<int:c_id>/unhold", views.unhold, name="unhold"),
]

schedule/models.py
from django.db import models
from django.contrib.auth.models import User

class FlatMate(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Name = models.CharField(max_length=200)
    Available = models.IntegerField(default=1, help_text="set to 0 if this mate is away")
    Contact = models.CharField(max_length=200, blank=True)
    Points = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.Name

    def is_available(self):
        return self.Available == 1

class Room(models.Model):
    Name = models.CharField(max_length=200)
    Interval = models.IntegerField(help_text="this room should be cleaned every ... days")
    Cleaner = models.ForeignKey(FlatMate, on_delete=models.SET_NULL, null=True, blank=True, help_text="this room is assigned to flatmate ...")
    Since = models.DateTimeField(help_text="since when this room is assigned to the flatmate")
    Done = models.IntegerField(default=0)
    
    def __str__(self):
        return self.Name

    def is_done(self):
        return self.Done == 1

schedule/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse

from .models import Room, FlatMate
test=False

def index(req, test=test):
    """
    Display Room/FlatMate tables.
    """
    if test==True:
        return HttpResponse("<h1>Add FLatmates!</h1>")
    Rooms = Room.objects.all()
    
    now = timezone.now().date()
    timeleft = {r.id: abs((now - r.Since.date()).days - r.Interval) for r in Rooms}
    Mates = FlatMate.objects.all()
    context =  {'rooms': Rooms, 'flatmates': Mates, 'timeleft': timeleft}
    return render(req, "schedule/index.html", context)

def done(req, room_id):
    """
    Set a Room to Done.
    """
    Room_obj = get_object_or_404(Room, pk=room_id)
    Room_obj.Done = 1
    Room_obj.save()
    return index(req)

def rotate(req, room_id):
    """
    Rotate a Task thats 'Done' to the next Mate.
    """
    # map each mate to his neighbouring mate
    mates_list = [mate.id for mate in FlatMate.objects.all().only("id")]
    mates_dict = {mates_list[index]: mates_list[index+1] for index, _ in enumerate(mates_list[:-1])}
    mates_dict[mates_list[-1]] = mates_list[0]
    # TODO check that each index only occurs once
    now = timezone.now()
    Room_obj = get_object_or_404(Room, pk=room_id)
    currentmate = Room_obj.Cleaner_id 
    nextmate = mates_dict[currentmate]
    if len(FlatMate.objects.filter(Available=1)) != 0:
        Room_obj.Cleaner_id = nextmate
        Room_obj.Done = 0
        Room_obj.Since = now
        Room_obj.save()
    else:
        return index(req)  # TODO print message that all flatmates are on vacation
    if FlatMate.objects.filter(pk=nextmate).values_list("Available")[0][0] == 1:
        return index(req)
    elif len(FlatMate.objects.filter(Available)) != 0:
        return rotate(req, room_id)

def hold(req, c_id):
    """
    Make a Flatmate not available.
    """
    FlatMate.objects.filter(pk=c_id).update(Available=0)
    return index(req)

def unhold(req, c_id):
    """
    Make a Flatmate available.
    """
    FlatMate.objects.filter(pk=c_id).update(Available=1)
    return index(req)

schedule/templates/schedule/index.html
<!DOCTYPE html>
{% load clean_tt %}
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<title>Cleaning Schedule</title>
</head>
<body>
<div class="container">
<div class="jumbotron">
<h1>Cleaning Schedule</h1>
<table class="table table-striped">
<thead>
<tr><th>Task</th> <th>assigned to</th> <th>Status</th></tr>
<tbody>
{% for r in rooms %}
<tr>
</thead>
<td>{{r.Name}}</td> <td> {{r.Cleaner}}</td>
<td>
{% if r.Done == 1 %}
    &#10004;
    {% else %}
        {% if timeleft|get:r.id <= r.Interval %}
            {{timeleft|get:r.id}} days til due
            {% else %}
            {{timeleft|get:r.id}} days overdue!
        {% endif %}
{% endif %}
</td> 
<td>
{% if r.Done == 0%}
<form action="{% url 'schedule:done' r.id %}" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-success" name="done" id={{ r.Name }} value="Done!">
</form>
{% else %}
<form action="{% url 'schedule:rotate' r.id %}" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn " value="Rotate">
</form>
{% endif %}
</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>

<div class="container">
   <h2>Flatmate Availability</h2>
   
    <table class="table table-bordered">
        <thead>
        <tr><th>Flatmate</th></tr></thead>
        <tbody>
        {% for mate in flatmates %}
        <tr>
            {% if mate.Available == 1 %}
                <td>{{mate.Name}}</td>
                <td>
                    <form action="{% url 'schedule:hold' mate.id %}" method="POST">{% csrf_token %}
                     <input type="submit" class="btn btn-primary" value="Not at home">
                    </form>
                </td>
            {% else %}
                <td><del>{{mate.Name}}</del></td>
                <td>
                     <form action="{% url 'schedule:unhold' mate.id %}" method="POST">{% csrf_token %}
                       <input type="submit" class="btn" value="Back again">
                     </form>
                </td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    <table>
</div>
</body>
</html>